# Generated by Django 4.0.5 on 2022-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('FS', 'Первое'), ('SC', 'Второе'), ('DR', 'Питье')], default=('FS', 'Первое'), max_length=2, verbose_name='тип еды'),
        ),
    ]
